services:
  kafka_django:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./source/core:/app
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db
      - kafka
    networks:
      - internal
      - kafka-network

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    expose:
      - "5432"
    networks:
      - internal

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

networks:
  internal: null
  kafka-network:
    driver: bridge